# Generated by Django 4.1.6 on 2023-02-04 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('muscle', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('dni', models.IntegerField(max_length=8, null=True)),
                ('phone', models.IntegerField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_plan', models.CharField(choices=[('2XW', 'Two times a week'), ('3XW', 'Three timees a week'), ('UNL', 'Unlimited')], max_length=3)),
                ('estado', models.BooleanField(default=False)),
                ('dia_vencimiento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('dni', models.IntegerField(max_length=8, null=True)),
                ('phone', models.IntegerField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('emergency_contact', models.IntegerField(max_length=15, null=True)),
                ('health_file', models.FileField(upload_to='')),
                ('suscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='susccription', to='home.suscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Routines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.exercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('method', models.CharField(choices=[('E', 'Cash'), ('C', 'Credit card'), ('D', 'Debit card')], max_length=1)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
    ]
