# Generated by Django 4.1.6 on 2023-02-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dni',
            field=models.IntegerField(max_length=8, null=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='emergency_contact',
            field=models.IntegerField(max_length=15, null=True, verbose_name='Contacto de emergencia'),
        ),
        migrations.AlterField(
            model_name='student',
            name='health_file',
            field=models.FileField(upload_to='', verbose_name='Ficha medica'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(max_length=15, null=True, verbose_name='Teléfono'),
        ),
    ]
