# Generated by Django 4.1.6 on 2023-02-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_student_health_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='health_file',
            field=models.FileField(upload_to='', verbose_name='Ficha medica'),
        ),
    ]
