# Generated by Django 4.1.6 on 2023-02-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_exercise_link_alter_exercise_muscle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='health_file',
            field=models.FileField(upload_to='gym_manager_project/apps/static/assets/health_files', verbose_name='Ficha medica'),
        ),
    ]
