# Generated by Django 4.1.6 on 2023-02-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_student_suscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='suscription',
            field=models.CharField(choices=[(100, 'UNL'), (12, '3XW'), (8, '2XW')], max_length=3),
        ),
    ]
