# Generated by Django 4.1.6 on 2023-02-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_student_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rutine',
            field=models.FileField(null=True, upload_to='rutines', verbose_name='Plan de entrenamiento'),
        ),
    ]
