# Generated by Django 4.1.6 on 2023-02-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_student_rutine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='rutine',
            new_name='routine',
        ),
        migrations.RemoveField(
            model_name='routines',
            name='exercises',
        ),
        migrations.AddField(
            model_name='student',
            name='routine_st',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Dia')),
                ('exercise', models.ManyToManyField(to='home.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='routines',
            name='day',
            field=models.ManyToManyField(to='home.day'),
        ),
    ]
