# Generated by Django 4.1.6 on 2023-02-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_rutine_student_routine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restTime', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='reps',
            field=models.ManyToManyField(to='home.reps'),
        ),
        migrations.AddField(
            model_name='day',
            name='restTime',
            field=models.ManyToManyField(to='home.resttime'),
        ),
    ]
