# Generated by Django 4.1.6 on 2023-02-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
